name: front_matter
version: 1.1.0
description: A front matter parser that extracts YAML metadata from the start of a file or string.
homepage: https://github.com/izolate/front-matter
documentation: https://github.com/izolate/front-matter/blob/master/README.md
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  yaml: ^3.0.0
dev_dependencies:
  test: ^1.6.2
